# Netlify configuration for FootTour (static site)

[build]
  command = ""
  publish = "."

# Because we use hash-based routes (/#/...), no SPA redirects are required.
# If later you switch to history API routes, add:
# [[redirects]]
#   from = "/app/*"
#   to = "/index.html"
#   status = 200
# [[redirects]]
#   from = "/t/*"
#   to = "/index.html"
#   status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval'; connect-src https:; img-src 'self' https: data:;"
